apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-k8s-deployment
  name: spring-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-k8s-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-k8s-deployment
    spec:
      containers:
      - image: docker.io/library/spring-k8s:0.0.1-SNAPSHOT
        name: spring-k8s
        resources: {}
status: {}
