apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-k8s-deployment
  name: spring-k8s-deployment
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-k8s-deployment
  type: LoadBalancer
  externalIPs:
    - 192.168.59.101
status:
  loadBalancer: {}
